### ISSUE TITLE
Software Heritage

### ISSUE THREAD

**Issue by adatario** [ocaml/opam-source-archives#15]
Might be interesting to see how this effort could be joined with work done by Sotware Heritage (https://www.softwareheritage.org/) - an organization that is dedicated to preserving software.

**Comment by kit-ty-kate** [comment]
Yes, softwareheritage support is coming in the upcoming opam 2.2.0. See https://github.com/ocaml/opam/pull/4859

**Comment by adatario** [comment]
Neat!
